version: "3.7"
services:
  main:
    restart: always
    build: ./ShareToDoList
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: app_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 'jj123100!!'
      MYSQL_DATABASE: 'todolist'

  node:
     restart: always
     build: ./chat
     depends_on:
       - mysql
     ports:
       - "1230"

#  mysql:
#    build: ./mysql
#    restart: unless-stopped
#    container_name: app_mysql
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./mysql/mysql_data:/var/lib/mysql
#      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
#    environment:
#      MYSQL_ROOT_PASSWORD: jj123100!!
#      MYSQL_DATABASE: todolist
