CREATE DATABASE IF NOT EXISTS todolist;
USE todolist;

CREATE TABLE `member` (
   `ID` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `PWD` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
   PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
CREATE TABLE `roomlist` (
   `rno` INT(10) NOT NULL AUTO_INCREMENT,
   `host` VARCHAR(200) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `title` VARCHAR(200) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
   PRIMARY KEY (`rno`) USING BTREE,
   INDEX `roomName` (`host`) USING BTREE,
   CONSTRAINT `roomName` FOREIGN KEY (`host`) REFERENCES `todolist`.`member` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=70
;
CREATE TABLE `plan` (
   `PNO` INT(10) NOT NULL AUTO_INCREMENT,
   `RNO` INT(10) NOT NULL,
   `text` VARCHAR(200) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
   `isChecked` TINYINT(1) NOT NULL default 0,
   PRIMARY KEY (`PNO`) USING BTREE,
   INDEX `RNO` (`RNO`) USING BTREE,
   CONSTRAINT `plan_ibfk_1` FOREIGN KEY (`RNO`) REFERENCES `todolist`.`roomlist` (`rno`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
